# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

resources:
  repositories:
    - repository: templates
      type: github
      name: miika3l/azure-pipelines-templates
      endpoint: miika3l # Azure DevOps service connection

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '6a6a3c80-0099-4495-b0fb-761da697cf53'

  # Web app name
  webAppName: 'helloworld-nodejs-24602'

  # Environment name
  environmentName: 'helloworld-nodejs-24602'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - template: node-build.yml@templates  # Template reference

# - stage: Deploy
#   displayName: Deploy stage
#   dependsOn: Build
#   condition: succeeded()
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy
#     environment: $(environmentName)
#     pool:
#       vmImage: $(vmImageName)
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureWebApp@1
#             displayName: 'Azure Web App Deploy: helloworld-nodejs-24602'
#             inputs:
#               azureSubscription: $(azureSubscription)
#               appType: webAppLinux
#               appName: $(webAppName)
#               runtimeStack: 'NODE|16-lts'
#               package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
#               startUpCommand: 'npm run start'